# Generated by Django 3.2.8 on 2021-11-27 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('advisor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Advisor_name', models.CharField(max_length=150)),
                ('Advisor_Photo_URL', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advisor', to='advisor.advisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
